### ISSUE TITLE
Error con Magento2 sobre PHP 5.6

### ISSUE THREAD

**Issue by ldglucas** [TodoPago/Plugin-Magento2#1]
Al habilitar el módulo desde la consola puedo configurarlo en el admin, pero el front, al momento de proceder al checkout queda con el gif de "loading" el sitio y da un error 500 en consola. ¿Estoy haciendo algo mal?

**Comment by barbanet** [comment]
El problema en Magento 2.1.1, al ingresar al checkout, estaría (creo) en el layout.
Se obtiene este error:

```
main.CRITICAL: Broken reference: No element found with ID 'checkout.header.wrapper'. [] []
```

**Comment by ldglucas** [comment]
Sigo con el problema. Log de PHP:
PHP Fatal error:  Class 'To
doPago\\Sdk' not found in app/code/Prisma/TodoPago/Model/Factory/Connector.php on line
 40

**Comment by barbanet** [comment]
Creo que la falla estaba con la ausencia del paquete todopago/php-sdk, que la instalación de todopago/plugin-magento2 no instaló las dependencias.
Una vez instalado el paquete del sdk, parece funcionar correctamente.

**Comment by danielruedaa** [comment]
Hola, al instalar el modulo todopago me genera el siguinete error
![image](https://cloud.githubusercontent.com/assets/22922863/23044889/37aeb5d0-f470-11e6-92ad-f9a13dc17700.png)

Intente actualizar usando 
               $ composer update
para generar el SDK y lugo actualizar con
   php bin/magento setup:upgrade
Pero no me funciono.

**Comment by asenosiain** [comment]
Hola, al querer configurar TodoPago para Development desde la consola de admin me da el error Class 'TodoPago\Sdk' not found (el mismo que se reporta arriba, pasa lo mismo con Production).

La versión de Magento que estoy utilizando es la 2.1.9, el cliente Soap está habilitado, y seguí los pasos para habilitar, instalar, compilar y hacer deploy del contenido.

Alguna idea dónde mirar qué puede estar faltando?

**Comment by barbazul** [comment]
@asenosiain Fijate si luego de instalar via composer tenes la carpeta `vendor/todopago/php-sdk`

Si no está, tenes algún tema por el cual no se te instaló la dependencia. Podés probar reinstalando el módulo `composer remove todopago/magento2-plugin; composer require todopago/magento2-plugin`.

En cambio, si la carpeta efectivamente se encuentra ahí, el problema estaría en el autoload. Podes probar tirando un `composer dump-autoload`.

**Comment by asenosiain** [comment]
Gracias @barbazul, probé instalando usando composer y se generó el directorio.
