### ISSUE TITLE
Para los que están teniendo problemas en el checkout cargando indefinidamente

### ISSUE THREAD

**Issue by macr1408** [TodoPago/Plugin-Magento2#11]
El error es debido a que el sdk de todopago no está presente al instalar el plugin manualmente. Existen dependencias.

Instalen el plugin usando composer y no van a tener problemas.

**Comment by barbazul** [comment]
Tener en cuenta que no tienen correctamente configurado el repositorio para que sincronice a Packagist con lo que si instalan simplemente con `composer require todopago/magento2-plugin` va instalar la version 1.5.0 y la ultima que salio es la 1.12.0

Para instalar la ultima version, se debe agregar la url del repositorio en el archivo composer.json del magento
