### ISSUE TITLE
No funciona con Magento 2.2.6

### ISSUE THREAD

**Issue by lgalant** [TodoPago/Plugin-Magento2#15]
Tienen pensado sacar una actualizacion?
Instale el plugin a mano tomando el codigo de github, y pude entrar a la configuracion de payment  methods (veo Todo Pago para configurar) pero recibo este error:
 PHP Fatal error:  Uncaught Error: Class 'TodoPago\Sdk' not found in /var/www/html/magento/app/code/Prisma/TodoPago/Model/Factory/Connector.php:40

Si lo hago con composer me instala el  php-sdk pero es una version mucho mas vieja y directamente no funciona nada

**Comment by curcio79** [comment]
@lgalant  buenos dias y disculpa por la falta de respuesta. El problema de la instalacion manual es la falta de la instalacion de las dependencias requeridas (si necesitas ayuda generame un nuevo issue y te paso las dependencias requeridas y lo trabajamos juntos). Sobre tu pregunta, si tenemos pensado sacar la actualizacion en el proximo mes. Saludos
