### ISSUE TITLE
Formato de campo CSBTIPADDRESS no válido

### ISSUE THREAD

**Issue by jrios74** [TodoPago/Plugin-Magento2#16]
Estoy obteniendo este error del módulo cuando el cliente intenta usar TodoPago:
[2018-11-28 02:28:56] main.DEBUG: TODOPAGO - MODEL PAYMENT - Response: {"StatusCode":98104,"StatusMessage":"El formato del campo CSBTIPADDRESS es incorrecto (IPV4)"} {"is_exception":false} []
Como se puede corregir el mismo, aclaro la version de magento es la 2.1.7 y la del módulo  instalado con composer es: "todopago/magento2-plugin": "^1.6.1"
Desde ya quedo a la espera de su pronta respuesta,saludos cordiales

**Comment by curcio79** [comment]
@jrios74 buenos dias y disculpa por la tardanza en la respuesta. El problema puede radicar en el uso de IPV6 en el campo CSBTIPADDRESS. Por el tiempo entre tu pregunta y la respuesta seguro lo resolviste. En caso negativo volve a levantarme un issue y lo resolvemos. Saludos
