### ISSUE TITLE
Da un error desconocido "Something went wrong, please try again later"

### ISSUE THREAD

**Issue by lbertran** [TodoPago/Plugin-Magento2#17]
Se puede probar en https://enviosaltoque.com.ar/enviosaltoque/. Muchas gracias.

**Comment by guillermoluced** [comment]
Hola Ibertran, en que punto aparece ese mensaje?, tenes activado el log para ver que esta mostrando?.

**Comment by lbertran** [comment]
Hola Guillermo, recien lo solucioné. Te comento, el error estaba en el telefono, si magento no tiene validación de longitud sobre este campo, el plugin de todo pago da errores con strings menores a 6 caracteres. 

FIX: La solución es validar el campo telefono de Magento.
