### ISSUE TITLE
Error con Magento 2.0 y 2.1

### ISSUE THREAD

**Issue by pedrodevoto** [TodoPago/Plugin-Magento2#3]
Cuando intento hacer una compra, antes de redirigirme a todopago, me devuelve al carrito con el error "Something went wrong, please try again later".

En los logs, veo que TodoPago responde lo siguiente: 

```json
{"StatusCode":98003,"StatusMessage":"Por favor contactese con el administrador para verificar los datos del cliente."}
```

Cuál puede ser el problema? Probé con ambas versiones mencionadas en el título.

**Comment by pedrodevoto** [comment]
El problema era con Guest Checkout, ya que los campos `CSBTCUSTOMERID` y `CSBTEMAIL` (y quizás otros), que son requeridos, no se completan correctamente. `CSBTCUSTOMERID` debería ser `guest` y `CSBTEMAIL` debería tomar el que se ingresa en el checkout, pero en cambio el plugin pretende obetener el email del usuario, que justamente no existe.

**Comment by drarko** [comment]
Estimado,

Revisaremos el comportamiento a la brevedad y haremos el hotfix
correspondientes.

Gracias

**Comment by drarko** [comment]
Estimado, se acaba de publicar una versión que corrige este problema. Si persiste, por favor, reabrir.

**Comment by drarko** [comment]
Hola TodoPago/Plugin-Magento2,
Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 
Haz click aqui a.iqelite.com/j/0NJf2L/h26/?hg=X69lDQsugm para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=9337e342&email=reply@reply.github.com.&hg=X69lDQsugm IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------

**Comment by drarko** [comment]
Hola TodoPago/Plugin-Magento2,


Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 


Haz click aqui a.iqelite.com/j/0NJf2L/h26/?hg=pkFmiWowxQ para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=9337e342&email=reply@reply.github.com.&hg=pkFmiWowxQ IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
