### ISSUE TITLE
Error en Instalación via composer.

### ISSUE THREAD

**Issue by freakpol** [TodoPago/Plugin-Magento2#4]
Pasos para reproducirlo

Crear un archivo composer.json que incluya un M2. 
Agrregar la dependencia del plugin "todopago/magento2-plugin": "1.2.3"
composer install

El codigo queda instalado tanto en vendor como en app/code.
Nos ha pasado tmabien que a veces si instala en subdirectorios dentro de app/code.

Solución propuesta:

Cambiar el composer.json, especificamente estas lineas

`
 "extra": {
        "map": [
            [
                "*",
                "Prisma/TodoPago"
            ]
        ]
    }
`
 por

`
"autoload": {
        "files": [ "registration.php" ],
        "psr-4": {
            "Prisma\\TodoPago\\": ""
        }
    }
`

Que, además, es la forma como la hacen los otros modulos de magento.

**Comment by drarko** [comment]
Incorporado, gracias por tu colaboracion.
Saludos
