### ISSUE TITLE
Error al obtener el estado de la orden desde backend

### ISSUE THREAD

**Issue by jpmayoral** [TodoPago/Plugin-Magento2#9]
Buenas! Al entrar al detalle de una orden en backend y obtener el Status de TodoPago está devolviendo una excepción. Parece q modificaron la info q devuelve ahora xq antes si funcionaba y no modificaron nada en las últimas actualizaciones del módulo.

El error es el siguiente: 
1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in /var/www/html/juleriaque/src/vendor/todopago/magento2-plugin/view/adminhtml/templates/status.phtml on line 36

Exception #0 (Exception): Notice: Array to string conversion in /var/www/html/juleriaque/src/vendor/todopago/magento2-plugin/view/adminhtml/templates/status.phtml on line 36.-

Habría q agregar una validación extra y parsear el array para que no pinche. Saludos!

**Comment by marcosvolpiok** [comment]
Hola  jpmayoral. Buenas tardes.
¿Qué versión del plugin y de Magento tenés instalado?

**Comment by jpmayoral** [comment]
Cómo andas Marcos! Tengo la v2.1.7 de Magento y la v1.5 de TodoPago. Composer está devolviendo esa versión y no la v1.6.0 (esto lo cargue en otro issue acá en github). 

https://github.com/TodoPago/Plugin-Magento2/issues/8

Saludos!
